export const START_INITIAL_LOAD = 'START_INITIAL_LOAD';
export const FINISH_INITIAL_LOAD = 'FINISH_INITIAL_LOAD';

export const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED';

export const NEW_UTC_SAVED = 'NEW_UTC_SAVED';
export const NEW_LOCATION_SAVED = 'NEW_LOCATION_SAVED';

export const DELETE_UTC = 'DELETE_UTC';
export const DELETE_LOCATION = 'DELETE_LOCATION';
